name: Setup dependencies
description: Download dependent libraries

runs:
  using: composite
  steps:
    - name: Cache lib directory
      uses: actions/cache@v4
      with:
        path: modules/Sentry/lib
        key: dependencies-${{ hashFiles('dependencies/**') }}

    - run: ./dependencies/download.ps1
      shell: pwsh
