name: Analysis

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name ConvertToSARIF -Force
          Import-Module -Name ConvertToSARIF -Force
          ./tools/init.ps1
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings PSGallery | ConvertTo-SARIF -FilePath results.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
