name: Analysis

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: microsoft/psscriptanalyzer-action@v1.0
        with:
          path: .
          recurse: true
          output: results.sarif
