name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.shell }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Test all Powershell (core) versions on Ubuntu
        os: [ubuntu-latest]
        shell: [pwsh]
        version:
          - '7.4.0'
          - '7.3.0'
          - '7.2.0'
          - '7.1.0'
          - '7.0.0'
          - '6.2.0'
          - '6.1.0'
          - '6.0.0'
        # And test all built-in PowerShell/Windows Powershell versions on latest CI runner images
        include:
          - os: ubuntu-latest
            shell: pwsh
          - os: macos-latest
            shell: pwsh
          - os: windows-2019
            shell: powershell
          - os: windows-2022 # same as windows-latest as of 02/2024
            shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Setup PowerShell
        if: ${{ matrix.version != '' }}
        uses: ./.github/actions/setup-powershell
        with:
          version: ${{ matrix.version }}

      - run: $PSVersionTable

        # We don't test module loading with Pester because we're unable to unload the module between tests.
        # Testing as a separate step allows unloads it automatically at the step end.
      - name: Module loading
        run: |
          # Loading the first time
          Get-Item ./module/Sentry.psd1 | Import-Module -PassThru
          # This needs to return actual types (method overloads)
          '[Sentry.SentrySdk]::init'
          # Loading the second time must be possible, without errors
          Get-Item ./module/Sentry.psd1 | Import-Module
          # And accessing APIs must still work too
          '[Sentry.SentrySdk]::init'

      - name: Unit tests
        run: |
          Get-Item ./module/Sentry.psd1 | Import-Module
          $config = New-PesterConfiguration
          $config.Run.Path = "tests"
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config
