name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.shell }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]
        shell: [pwsh]
        include:
          - os: windows
            shell: powershell

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

        # We don't test module loading with Pester because we're unable to unload the module between tests.
        # Testing as a separate step allows unloads it automatically at the step end.
      - name: Module loading
        run: |
          # Loading the first time
          Get-Item ./module/Sentry.psd1 | Import-Module -PassThru
          # This needs to return actual types (method overloads)
          '[Sentry.SentrySdk]::init'
          # Loading the second time must be possible, without errors
          Get-Item ./module/Sentry.psd1 | Import-Module
          # And accessing APIs must still work too
          '[Sentry.SentrySdk]::init'

      - name: Unit tests
        run: |
          Get-Item ./module/Sentry.psd1 | Import-Module
          $config = New-PesterConfiguration
          $config.Run.Path = "tests"
          $config.TestResult.Enabled = $true
          Invoke-Pester -Configuration $config
